### ISSUE TITLE
请问第106页，“粘包分包完整示例”测试中有没有出现过永远只显示最新一条消息的情况？

### ISSUE THREAD

**Issue by CaigerDeng** [luopeiyu/unity_net_book#4]
第106页有一句代码：
    recvStr = s + "\n" + recvStr
这句代码我打印出的recvStr 是最新一条信息内容，并没有包含历史消息。

**Comment by luopeiyu** [comment]
你好呀，会不会是text组件高度太小，导致只够显示一行呢？

**Comment by CaigerDeng** [comment]
还真不是，我Debug发现这里：
string s = System.Text.Encoding.UTF8.GetString(readBuff,2,buffCount);
转出来的s是有问题的，比如说输入hi（其实就是02hi），转出来的s.length常理来说是2，但其实是4，这就导致接下来对字符串s的打印、自加等操作可能都会有问题。

**Comment by luopeiyu** [comment]
明白了，此处确实有误。
原因在于string s = System.Text.Encoding.UTF8.GetString(readBuff,2,buffCount);这一句。此处应改为string s = System.Text.Encoding.UTF8.GetString(readBuff,2,bodyLength);

因为buffCount是整个缓冲区的长度，bodyLength才是某条消息的长度。
这个问题下一版印刷更正~

**Comment by CaigerDeng** [comment]
OK，谢谢解答
