### ISSUE TITLE
勘误+建议

### ISSUE THREAD

**Issue by CaigerDeng** [luopeiyu/unity_net_book#5]
非常感觉大佬写了这本书，它帮我梳理了这几年对框架的一个理解，也补了很多知识。我现在已经把它读完了，也把书上所有代码都测试了一遍。以下是对本书的勘误和建议，如果能对作者和正在学习它的人起到一些帮助就好了。

1)	第2页，图1-3，右边方框里“客户端”应为“服务端”
2)	第102页，图4-17，倒数两条缓冲区示意图是不是多余的？
3)	第221页，第一行，MysqlCommand cmd = new MysqlCommand(s , mysql)；这样写测试会有 There is already an open DataReader associated with this Connection which must be closed相关报错。虽然我在后面看到了有关闭DataReader的代码，但还是先用using (MysqlCommand cmd = new MysqlCommand(s , mysql) )通过测试会不会更好些？
4)	第281页，9.4.1第一段第二行，“分别有Layer.Panel和Layer.Panel两项”应为“分别有Layer.Panel和Layer.Tip两项”

一些建议：
1)	我在测试第三章大乱斗游戏时，已经发生了粘包问题，不过当时还没有看到第四章，所以我用自己的方法解决了问题。如果可以稍微提一句可能发生问题会在第XXX章介绍就好了。
2)	使用Unity2018（目前最新2018.3.11f1仍未修复）生成的exe，会有点击UI按钮不响应的问题，所以我的测试都是在2017.2.1f1版本上完成的。
3)	第六章介绍的Protobuf，一般大家都是想要批处理生成文件的吧，这里有一个Protobuf批处理工具[链接](https://github.com/654306663/ProtoGenToCs)

**Comment by luopeiyu** [comment]
感谢大大的勘误和建议。后面会整理出来，然后在第二次印刷中完善和更正。
