### ISSUE TITLE
第二版第8章的一些代码问题

### ISSUE THREAD

**Issue by 0kk470** [luopeiyu/unity_net_book#6]
首先感谢大大写了这本书，个人受益匪浅。
我在阅读第8章的过程中发现了一些小问题，希望能为勘误提供一些帮助。
p249移动控制坦克的最后一行代码
`transform.transform.position += s;` 
这里应该是多了个transform（虽然没影响）

另外p258的计算相机位置的代码遗漏了函数名,应该是调用的插值函数Vector3.Lerp
`cameraPos = (cameraPos,targetPos,Time.deltaTime * speed)`

**Comment by luopeiyu** [comment]
你好呢，这里确实是漏了。下一次印刷会修正它们，谢谢。（不太习惯关注Issues，后面我要多关注才行）
